## The first day in Davos

### put ; in the end of command to hide the result

In [41]:
using Distributions
nanimal = 6
nloci = 10
X = sample(0:2, (nanimal, nloci));  # sample the SNP codes

6x10 Array{Int64,2}:
 0  1  0  2  2  0  1  2  2  2
 1  1  0  0  0  2  0  1  0  1
 0  1  2  1  1  0  0  0  2  2
 2  0  2  2  2  1  2  2  1  0
 1  1  2  1  2  2  0  2  0  2
 0  1  0  0  1  0  1  2  2  1

In [30]:
# set the general mean
mu = ones(nanimal)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [31]:
mu = int(mu)  # chenge the code to integer

6-element Array{Int64,1}:
 1
 1
 1
 1
 1
 1

In [39]:
# add mu into X
X = hcat(mu, X)

6x11 Array{Int64,2}:
 1  0  0  0  0  2  0  2  1  1  2
 1  1  1  1  0  1  0  0  1  2  2
 1  2  0  1  2  0  2  2  1  1  1
 1  0  0  1  2  2  2  0  0  1  2
 1  1  2  0  0  1  1  0  2  2  0
 1  2  1  1  0  2  2  0  1  1  2

## simulate the SNP effects

In [37]:
# simulate the effect
me = 0.0; std = 0.5;
b = rand(Normal(me, std), nloci + 1)
length(b)

11

In [25]:
Base.mean(1:3) # if I over-write the mean function

2.0

## simulate the phenotype

In [40]:
resd = 1.0
y = X*b + rand(Normal(0, resd), nanimal)

6-element Array{Float64,1}:
 -0.276541
  1.18978 
 -0.251366
 -0.148648
 -0.643657
  1.29263 

In [1]:
ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## Write a function
$$y = Xb + e$$

In [14]:
using Distributions
function SimData(nanimal, nloci, bme, bsd, resd)
    X = [ones(nanimal, 1) sample(0:2, (nanimal, nloci))]
    srand(123) # set seed
    b = rand(Normal(bme, bsd), size(X, 2))
    e = rand(Normal(0, resd), size(X, 1))
    y = X*b + e
    return(y, X, b, e)
end

SimData (generic function with 1 method)

In [23]:
y = SimData(6, 4, 0, 2.5, 1)[1]
X = SimData(6, 4, 0, 2.5, 1)[2]
b = SimData(6, 4, 0, 2.5, 1)[3]

5-element Array{Float64,1}:
  2.97567 
  5.12045 
  2.85663 
  1.14854 
 -0.991698

In [21]:
eigvals(X'X)

5-element Array{Float64,1}:
  0.142095
  1.07244 
  2.0688  
  5.25476 
 43.4619  

In [22]:
bHat = X'X\X'y

5-element Array{Float64,1}:
  0.115631
  3.37424 
 -2.53874 
 -2.53291 
  9.85451 

In [24]:
cor(b, bHat)

-0.4367074639421907

In [25]:
rank(X'X)

5

In [26]:
X*bHat

6-element Array{Float64,1}:
  7.43141
 16.7186 
  9.11406
 14.1857 
 13.0556 
  9.10823

In [27]:
eig(X'X)

([0.142095,1.07244,2.0688,5.25476,43.4619],
5x5 Array{Float64,2}:
 -0.79652    0.257169  -0.406957    0.0914043  -0.354193
  0.193567  -0.380955   0.0360288   0.698348   -0.573077
  0.030697  -0.592628  -0.226107   -0.65551    -0.408695
 -0.177674   0.228784   0.821248   -0.226386   -0.436339
  0.543671   0.620635  -0.327896   -0.151696   -0.434404)

In [28]:
methods(eig)

# 1 method for generic function "eig":
eig(A::Union(Number,AbstractArray{T,2}),args...) at linalg/factorization.jl:591